#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/lua
TICK=/opt/renzfi/lua/tick.lua

start_service() {
	mkdir -p /tmp/renzfi /tmp/renzfi/sse /opt/renzfi/data /etc/renzfi

	procd_open_instance tick
	procd_set_param command "$PROG" "$TICK"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	restart
}
