export const SESSION_IDLE_TIMEOUT_MINUTES = 15;
export const SESSION_IDLE_WARNING_MINUTES = 13;

export const SESSION_IDLE_TIMEOUT_MS = SESSION_IDLE_TIMEOUT_MINUTES * 60 * 1000;
export const SESSION_IDLE_WARNING_MS = SESSION_IDLE_WARNING_MINUTES * 60 * 1000;
