/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutVouchersRouteImport } from './routes/_layout/vouchers'
import { Route as LayoutSystemSettingsRouteImport } from './routes/_layout/system-settings'
import { Route as LayoutSalesReportsRouteImport } from './routes/_layout/sales-reports'
import { Route as LayoutRouterSettingsRouteImport } from './routes/_layout/router-settings'
import { Route as LayoutPromoRatesRouteImport } from './routes/_layout/promo-rates'
import { Route as LayoutLogsRouteImport } from './routes/_layout/logs'
import { Route as LayoutFirmwareRouteImport } from './routes/_layout/firmware'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCoinSettingsRouteImport } from './routes/_layout/coin-settings'
import { Route as LayoutCaptivePortalRouteImport } from './routes/_layout/captive-portal'
import { Route as LayoutActiveUsersRouteImport } from './routes/_layout/active-users'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutVouchersRoute = LayoutVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemSettingsRoute = LayoutSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesReportsRoute = LayoutSalesReportsRouteImport.update({
  id: '/sales-reports',
  path: '/sales-reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRouterSettingsRoute = LayoutRouterSettingsRouteImport.update({
  id: '/router-settings',
  path: '/router-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPromoRatesRoute = LayoutPromoRatesRouteImport.update({
  id: '/promo-rates',
  path: '/promo-rates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLogsRoute = LayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFirmwareRoute = LayoutFirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoinSettingsRoute = LayoutCoinSettingsRouteImport.update({
  id: '/coin-settings',
  path: '/coin-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCaptivePortalRoute = LayoutCaptivePortalRouteImport.update({
  id: '/captive-portal',
  path: '/captive-portal',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActiveUsersRoute = LayoutActiveUsersRouteImport.update({
  id: '/active-users',
  path: '/active-users',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-users': typeof LayoutActiveUsersRoute
  '/captive-portal': typeof LayoutCaptivePortalRoute
  '/coin-settings': typeof LayoutCoinSettingsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/firmware': typeof LayoutFirmwareRoute
  '/logs': typeof LayoutLogsRoute
  '/promo-rates': typeof LayoutPromoRatesRoute
  '/router-settings': typeof LayoutRouterSettingsRoute
  '/sales-reports': typeof LayoutSalesReportsRoute
  '/system-settings': typeof LayoutSystemSettingsRoute
  '/vouchers': typeof LayoutVouchersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-users': typeof LayoutActiveUsersRoute
  '/captive-portal': typeof LayoutCaptivePortalRoute
  '/coin-settings': typeof LayoutCoinSettingsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/firmware': typeof LayoutFirmwareRoute
  '/logs': typeof LayoutLogsRoute
  '/promo-rates': typeof LayoutPromoRatesRoute
  '/router-settings': typeof LayoutRouterSettingsRoute
  '/sales-reports': typeof LayoutSalesReportsRoute
  '/system-settings': typeof LayoutSystemSettingsRoute
  '/vouchers': typeof LayoutVouchersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/active-users': typeof LayoutActiveUsersRoute
  '/_layout/captive-portal': typeof LayoutCaptivePortalRoute
  '/_layout/coin-settings': typeof LayoutCoinSettingsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/firmware': typeof LayoutFirmwareRoute
  '/_layout/logs': typeof LayoutLogsRoute
  '/_layout/promo-rates': typeof LayoutPromoRatesRoute
  '/_layout/router-settings': typeof LayoutRouterSettingsRoute
  '/_layout/sales-reports': typeof LayoutSalesReportsRoute
  '/_layout/system-settings': typeof LayoutSystemSettingsRoute
  '/_layout/vouchers': typeof LayoutVouchersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-users'
    | '/captive-portal'
    | '/coin-settings'
    | '/dashboard'
    | '/firmware'
    | '/logs'
    | '/promo-rates'
    | '/router-settings'
    | '/sales-reports'
    | '/system-settings'
    | '/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-users'
    | '/captive-portal'
    | '/coin-settings'
    | '/dashboard'
    | '/firmware'
    | '/logs'
    | '/promo-rates'
    | '/router-settings'
    | '/sales-reports'
    | '/system-settings'
    | '/vouchers'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/active-users'
    | '/_layout/captive-portal'
    | '/_layout/coin-settings'
    | '/_layout/dashboard'
    | '/_layout/firmware'
    | '/_layout/logs'
    | '/_layout/promo-rates'
    | '/_layout/router-settings'
    | '/_layout/sales-reports'
    | '/_layout/system-settings'
    | '/_layout/vouchers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/vouchers': {
      id: '/_layout/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof LayoutVouchersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system-settings': {
      id: '/_layout/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof LayoutSystemSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales-reports': {
      id: '/_layout/sales-reports'
      path: '/sales-reports'
      fullPath: '/sales-reports'
      preLoaderRoute: typeof LayoutSalesReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/router-settings': {
      id: '/_layout/router-settings'
      path: '/router-settings'
      fullPath: '/router-settings'
      preLoaderRoute: typeof LayoutRouterSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/promo-rates': {
      id: '/_layout/promo-rates'
      path: '/promo-rates'
      fullPath: '/promo-rates'
      preLoaderRoute: typeof LayoutPromoRatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/logs': {
      id: '/_layout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LayoutLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/firmware': {
      id: '/_layout/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof LayoutFirmwareRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coin-settings': {
      id: '/_layout/coin-settings'
      path: '/coin-settings'
      fullPath: '/coin-settings'
      preLoaderRoute: typeof LayoutCoinSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/captive-portal': {
      id: '/_layout/captive-portal'
      path: '/captive-portal'
      fullPath: '/captive-portal'
      preLoaderRoute: typeof LayoutCaptivePortalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/active-users': {
      id: '/_layout/active-users'
      path: '/active-users'
      fullPath: '/active-users'
      preLoaderRoute: typeof LayoutActiveUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutActiveUsersRoute: typeof LayoutActiveUsersRoute
  LayoutCaptivePortalRoute: typeof LayoutCaptivePortalRoute
  LayoutCoinSettingsRoute: typeof LayoutCoinSettingsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutFirmwareRoute: typeof LayoutFirmwareRoute
  LayoutLogsRoute: typeof LayoutLogsRoute
  LayoutPromoRatesRoute: typeof LayoutPromoRatesRoute
  LayoutRouterSettingsRoute: typeof LayoutRouterSettingsRoute
  LayoutSalesReportsRoute: typeof LayoutSalesReportsRoute
  LayoutSystemSettingsRoute: typeof LayoutSystemSettingsRoute
  LayoutVouchersRoute: typeof LayoutVouchersRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutActiveUsersRoute: LayoutActiveUsersRoute,
  LayoutCaptivePortalRoute: LayoutCaptivePortalRoute,
  LayoutCoinSettingsRoute: LayoutCoinSettingsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutFirmwareRoute: LayoutFirmwareRoute,
  LayoutLogsRoute: LayoutLogsRoute,
  LayoutPromoRatesRoute: LayoutPromoRatesRoute,
  LayoutRouterSettingsRoute: LayoutRouterSettingsRoute,
  LayoutSalesReportsRoute: LayoutSalesReportsRoute,
  LayoutSystemSettingsRoute: LayoutSystemSettingsRoute,
  LayoutVouchersRoute: LayoutVouchersRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
